version: '3.9'

services:
  ganache:
    build:
      context: ./ganache
      dockerfile: Dockerfile.ganache
    container_name: ganache
    ports:
      - "7545:7545"
    volumes:
      - ganache-data:/ganache
    networks:
      - blockchain
    # command: >
    #   ganache --port 7545 --accounts 20 --defaultBalanceEther 200 --chain.chainId 581234 --chain.networkId 581234 --mnemonic "One Ring to rule them all, One Ring to find them, One Ring to bring them all and in the darkness bind them."
    #   > ganache-output.log 2>&1


  truffle:
    build:
      context: ./truffle
      dockerfile: Dockerfile.truffle
    container_name: truffle
    volumes:
      - truffle-data:/truffle
      - ganache-data:/ganache
    depends_on:
      - ganache
    working_dir: /truffle
    # command: />
    #   truffle migrate --reset --network development
    networks:
      - blockchain

  # csharp:
  #   build:
  #     context: ./C#block
  #     dockerfile: Dockerfile.C#
  #   container_name: csharp
  #   volumes:
  #     - ganache-data:/ganache
  #     - truffle-data:/truffle
  #   depends_on:
  #     - truffle
  #     - ganache
  #   working_dir: /app
  #   command: >
  #     dotnet run
  #   networks:
  #     - blockchain

volumes:
  ganache-data:
  truffle-data:

networks:
  blockchain: